title: 'Aar칩n Sosa Blog'
default_lang: es
author:
  name: 'Aar칩n Sosa'
  email: aasoru@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Blog personal de Aar칩n Sosa - Desarrollo de software y algo m치s'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
